services:
  pyspark:
    hostname: pyspark
    container_name: pyspark_container
    build: 
       context: .
       dockerfile: Dockerfile
    image: pyspark_custom_pacmann
    restart: on-failure
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - 8888:8888
      - 4040:4040
    volumes:
      - ./script:/home/jovyan/work
    networks:
      - my_network

  source_db:
    image: postgres:latest
    hostname: source_db
    container_name: source_db_container
    restart: on-failure
    environment:
      - POSTGRES_DB=${SRC_DB_NAME}
      - POSTGRES_USER=${SRC_DB_USER}
      - POSTGRES_PASSWORD=${SRC_DB_PASSWORD}
    volumes:
      - ./source/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${SRC_DB_PORT}:5432 
    networks:
      - my_network

  data_warehouse:
    image: postgres:latest
    hostname: data_warehouse
    container_name: data_warehouse_container
    restart: on-failure
    environment:
      - POSTGRES_DB=${WH_DB_NAME}
      - POSTGRES_USER=${WH_DB_USER}
      - POSTGRES_PASSWORD=${WH_DB_PASSWORD}
    volumes:
      - ./warehouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${WH_DB_PORT}:5432 
    networks:
      - my_network

  log_db:
    image: postgres:latest
    hostname: data_warehouse
    container_name: log_db
    restart: on-failure
    environment:
      - POSTGRES_DB=${LOG_DB_NAME}
      - POSTGRES_USER=${LOG_DB_USER}
      - POSTGRES_PASSWORD=${LOG_DB_PASSWORD}
    volumes:
      - ./log_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${LOG_DB_PORT}:5432 
    networks:
      - my_network
  
networks:
  my_network:
    driver: bridge